# Generated by Django 5.1.4 on 2024-12-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Tenants', 'Tenants'), ('Landlord', 'Landlord')], default='User', max_length=100),
        ),
    ]
