# Generated by Django 5.1.4 on 2024-12-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Tenants', 'Tenants'), ('Landroad', 'Landroad')], default='User', max_length=100),
        ),
    ]
