# Generated by Django 5.1.4 on 2024-12-29 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_maintenancerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
