# Generated by Django 5.1.4 on 2024-12-29 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyApp', '0008_maintenancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='PropertyApp.tenant'),
        ),
    ]
